[package]
name = "voice_input"
version = "0.1.0"
edition = "2024"

[dependencies]
device_query = "1.1.0"
tokio = { version = "1.28.0", features = ["full"] }
tokio-tungstenite = "0.19.0"
futures = "0.3.28"
url = "2.3.1"
once_cell = "1.17.1"
cpal = "0.15.3"
hound = "3.5.1"
chrono = "0.4.40"
reqwest = { version = "0.11", features = ["multipart", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
clap = { version = "4.5", features = ["derive"] }
arboard = "3.5.0"
ctrlc = "3.4"
sysinfo = "0.34.2"
