[package]
name = "voice_input"
version = "0.1.0"
edition = "2024"

[dependencies]
device_query = "1.1.0"
tokio = { version = "1.28.0", features = ["full"] }
tokio-tungstenite = "0.19.0"
futures = "0.3.28"
url = "2.3.1"
once_cell = "1.17.1"
cpal = "0.15.3"
clippy = "0.0.302"
hound = "3.5.1"
chrono = "0.4.40"
