[package]
name = "voice_input"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs" # 既存ライブラリ

# ─────────────────────────────────────────
# 実行バイナリ（全て [[bin]] で列挙）
# ─────────────────────────────────────────
[[bin]]
name = "voice_input" # クライアント CLI
path = "src/main.rs"

[[bin]]
name = "voice_inputd"            # 常駐デーモン
path = "src/bin/voice_inputd.rs"

[[bin]]
name = "migrate_dict"           # 辞書マイグレーション
path = "src/bin/migrate_dict.rs"

# ─────────────────────────────────────────
# 依存クレート ― ご指定をそのまま使用
# ─────────────────────────────────────────
[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
futures = "0.3.28"
cpal = "0.15.3"
hound = "3.5.1"
reqwest = { version = "0.11", features = ["multipart", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15.0"
clap = { version = "4.5", features = ["derive"] }
arboard = "3.5.0"
tokio-util = { version = "0.7", features = ["codec"] }
directories = "6.0.0"
scopeguard = "1.2.0"

# Apple Music制御用（macOSのみ・段階的移行中のため現在は無効）
# [target.'cfg(target_os = "macos")'.dependencies]
# swift-bridge = { version = "0.1", optional = true }

# [build-dependencies]
# Apple Music制御用ビルド設定（macOSのみ・段階的移行中のため現在は無効）
# [target.'cfg(target_os = "macos")'.build-dependencies]
# swift-bridge-build = { version = "0.1", optional = true }

# [features]
# default = ["native-music"]
# native-music = ["swift-bridge", "swift-bridge-build"]

[dev-dependencies]
tempfile = "3.8"
